### PR TITLE
feat(build): Support building multiple architectures via Docker buildx

### PR DESCRIPTION
**Pull request by tibuntu**
Hey,

I did find your webhook integration for netcup while setting up cert-manager in my local cluster.

However, since my cluster is running on an Raspberry Pi 4 and hence on arm architecture, I couldn't use your implementation because the Docker image was only build for amd64.

I've tweaked the build process a little bit in order to be compatible with multiple architectures.

As you can see, I only added support for arm/v7, you might want to extend the `--platform` argument for other architectures, too.

You can see my test image here: https://hub.docker.com/r/tibuntu/cert-manager-webhook-netcup/tags

Best regards!

### CODE REVIEW

**Comment by tibuntu** [comment]
Forgot to mention that you can see the image released by me here: https://hub.docker.com/repository/docker/tibuntu/cert-manager-webhook-netcup

**Comment by aellwein** [comment]
@tibuntu this is a very nice addition, thank you!

**Comment by aellwein** [comment]
I'll add some more architectures and release the images + Helm chart.

**Comment by aellwein** [comment]
@tibuntu new release 1.0.7 can now be found on ArtifactHub.

**Pull request merged**
